### ISSUE TITLE
Shell - Clone off of existing shell, not just template

### ISSUE THREAD

**Issue by graboskyc** [QualiSystems/shellfoundry#119]
Feature Request

Currently you can build a new shell off of pre-defined templates created by Quali. It would be nice to have a CLI flag to point to an existing shell directory and clone off of that. This would be good for custom shells and would update the XML in all the required places for the new name of the shell.

Thanks

**Comment by alonagetzler** [comment]
Hi
In the coming CloudShell release (8.2) we plan to add extend command to shellfoundry that will allow extending (fork+clone) official 2nd gen shells.
Alona

**Comment by kalsky** [comment]
this was implemented, you can use the extend command.
