### ISSUE TITLE
Password field should be encrypted

### ISSUE THREAD

**Issue by johnathanvidu** [QualiSystems/shellfoundry#121]
### Issue details
As a user I want the be able to configure a password via config command (#99) and that shellfoundry will encrypt the password.

* encryption should be very simple
* password should be encrypted when viewing config,yml (both local and global) in text editor

**Comment by johnathanvidu** [comment]
@ronenquali what about cases that the user already update his local config file with a password? this change will break his configuration.

**Comment by ronenquali** [comment]
@johnathanvidu Maybe we can add a different field for encrypted password and fallback to the old unencrypted one or detect whether the field is encrypted or not, I think we do something similar in studio.
