### ISSUE TITLE
Support '.' to create a project in current dir

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/shellfoundry#16]
### Issue details

We want it to be possible to support the flow of first creating a sub directory and then running shellfoundry to initialize the project structure inside it.

### Steps to reproduce

user creates a new directory 'nut-shell'
cd 'nut-shell'
run 'shellfoundry c . '
expected: initialize current directory as nut-shell

### Affected platforms

- [ ] Windows
- [ ] Linux

**Comment by borismod** [comment]
@doppleware do you mean?

```bash
$ shellfoundry new .
```

**Comment by borismod** [comment]
Fixed
