### ISSUE TITLE
run "python -m pip install -r" when generating the shell tempalte

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/shellfoundry#17]
### Issue details

To make the shell usable right from the start, it would be helpful to install the shell template dependencies.

Lets run "python -m pip install -r .\src\requirements.txt if requirements.txt exists in the template...

### Steps to reproduce

Run shellfoundry on a new system, try to use it , see it fails because of missing requirements

### Affected platforms

- [ X] Windows
- [ X] Linux

_Please fill additional environment specific configuration_

**Comment by borismod** [comment]
@doppleware do you think it's still relevant with the introduction of the dist command?

**Comment by doppleware** [comment]
The idea was to install it when doing 'new' but you might not be using the same Python in dev so on second thought I'm closing the issue.
