### ISSUE TITLE
No help for config method

### ISSUE THREAD

**Issue by graboskyc** [QualiSystems/shellfoundry#172]
### Issue details

There is no help built in for https://qualisystems.github.io/devguide/shells/8.1.0/getting-started.html on how to configure the server settings. This is now required with 1.0.3 so help must be provided in order to figure out how to use it

### Steps to reproduce

Run `shellfoundry config help` and realize no help is given

### Affected version:
1.0.3

**Comment by alonagetzler** [comment]
Hi

To get the config command help you should run `shellfoundry config --help`
Anyway, the current description of the command isn't good and we are going to fix it (will update this issue once its done). Soon we will also publish an article about shellfoundry in our devguide - https://qualisystems.github.io/devguide/

Alona
