### ISSUE TITLE
Class name is not capitalized correctly

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/shellfoundry#18]
### Issue details

I ran ShellFoundry to generate a new shell but the Python class name does not meet convention.

### Steps to reproduce

Run 'shellfoundry new linux-server-shell'
Expected class name in driver.py: Linux**S**erver**Shell**Driver
Actual: Linuxservershelldriver

### Affected version:

All
### Affected platforms

- [X ] Windows
- [X] Linux

_Please fill additional environment specific configuration_

**Comment by borismod** [comment]
Fixed
