### ISSUE TITLE
Png files are not copied from the datamodel folder to the package

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/shellfoundry#21]
### Issue details

As a user i would like to have a picture for my resource models imported with my shell. currently, i'm specifing a png file within the datamodel.xml and add the png to the datamodel folder in the project but when running the 'shellfoundry pack' command, the file is not copied to the pack and the import to cloudshell will fail.

### Steps to reproduce

1) add "ImagePath="a.png" " to the datamodel.xml for specific model
2) add an a.png file to the datamodel folder
3) run "shellfoundry pack"
4) try to import the pack

**Comment by borismod** [comment]
@TomerAdmon thanks for discovering it. Do you want to brush up your TDD skills in Python by contributing to shellfoundry :question:

**Comment by doppleware** [comment]
This should now work
