### ISSUE TITLE
zip file from build added to source code

### ISSUE THREAD

**Issue by tim-spiglanin** [QualiSystems/shellfoundry#225]
(contributions by Roni)
### Issue details

Build the shell - a wild file will appear and make its way to your source code

### Steps to reproduce
(Follow steps at own risk)

Create a new shell using shellfoundry new
Build the shell using shellfoundry install or shellfoundry pack
Observe a new file manifest in your root directory 
Watch as that file automatically gets checked in on your next commit much to the chagrin of your fellow developers
Weep as you realize git does not let you remove all traces of it even though you might remove it from the branch
Give up. Find a different vocation.

### Affected version:

shellfoundry version 1.2.4

### Affected platforms

- [X] Windows
- [X] Linux

_Please fill additional environment specific configuration_

Suggestions:
First add it to the .gitignore
Then consider not putting the zip in the root directory
Why do we even need this file in addition to the one in /dist? Is this a temp artifact of the build process?

**Comment by Costya-Y** [comment]
In the upcoming version of shellfoundry, we added functionality that will remove driver.zip once shellfoundry pack will be finished.
