### ISSUE TITLE
SetuptoolsVersion was removed from the latest versions of setuptools

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/shellfoundry#233]
### Issue details
fyi, it's being used in some of the files (like in template_retriever.py), and it's not supported anymore (removed) - so if you happen to have setuptools>38.7 on your machine, things will fail.

**Comment by Costya-Y** [comment]
Hi @kalsky,

Please clarify which shellfoundry version are you talking about?

Thanks

**Comment by kalsky** [comment]
I checked again and it looks ok now.

**Comment by Costya-Y** [comment]
Thank you @kalsky
