### ISSUE TITLE
yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/shellfoundry#234]
### Issue details
getting the following warning when trying to install/pack/generate:

LoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(stream.read())

c:\program files (x86)\qualisystems\testshell\executionserver\python\2.7.10\lib\site-packages\shellfoundry\utilities\template_retriever.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(response)

**Comment by Costya-Y** [comment]
Hi @kalsky 

Thank you for reporting this issue.
We will investigate and get back to you.

Thank you,
Costya

**Comment by Costya-Y** [comment]
Hi Yaniv,

We've added this to our backlog for one of the next releases.

Thank you,
Costya

**Comment by Costya-Y** [comment]
Fixed in the latest release
