### ISSUE TITLE
Shells based on Gen1 template is not able to install to CloudShell

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/shellfoundry#249]
### Issue details

If shell is created on Gen 1 template it isn't able to install with follow error:
_Error: Failed to install shell. CloudShell responded with: ''utf-8' codec can't decode byte 0xe5 in position 1: invalid continuation byte'_

### Steps to reproduce

1. Create shell which based on some Gen1 template
<pre>
(shellfoundry_1.2.16) C:\Users\dmit\Documents\Virtual_env\shellfoundry_1.2.16>shellfoundry new test_gen1 --template gen1/resource
Created shell test_gen1 based on template gen1/resource
</pre>

2. Perform Install command
<pre>
(shellfoundry_1.2.16) C:\Users\dmit\Documents\Virtual_env\shellfoundry_1.2.16\test_gen1>shellfoundry install
Shell package was successfully created:
C:\Users\dmit\Documents\Virtual_env\shellfoundry_1.2.16\test_gen1\dist\test_gen1.zip
Using local configuration...
Error: Failed to install shell. CloudShell responded with: ''utf-8' codec can't decode byte 0xe5 in position 1: invalid continuation byte'
</pre>
### Affected version:
Shellfoundry 1.2.16

- [x] Windows
- [ ] Linux

_Please fill additional environment specific configuration_

**Comment by Costya-Y** [comment]
Completed

**Comment by turkovda** [comment]
Verified and passed on 1.2.17.

<pre>
(venv) C:\Users\dmit\PycharmProjects\pytest_framework>pip install shellfoundry --upgrade
Collecting shellfoundry
  Downloading https://files.pythonhosted.org/packages/8b/91/aece295985c58ebeaf9899c03c84d10a80cfba3e118a25728ffe2986e009/shellfoundry-1.2.17.zip (121kB)
    100% |████████████████████████████████| 122kB 1.1MB/s
Requirement already satisfied, skipping upgrade: requests in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (2.22.0)
Requirement already satisfied, skipping upgrade: cookiecutter==1.6.0 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (1.6.0)
Requirement already satisfied, skipping upgrade: click==6.7 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (6.7)
Requirement already satisfied, skipping upgrade: pyyaml in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (5.3)
Requirement already satisfied, skipping upgrade: terminaltables in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (3.1.0)
Requirement already satisfied, skipping upgrade: cloudshell-rest-api>=8.2.3.1 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (8.2.4.0)
Requirement already satisfied, skipping upgrade: colorama in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (0.4.3)
Requirement already satisfied, skipping upgrade: giturlparse.py in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (0.0.5)
Requirement already satisfied, skipping upgrade: ruamel.yaml in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (0.16.7)
Requirement already satisfied, skipping upgrade: cryptography in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from shellfoundry) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from requests->shellfoundry) (1.25.8)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from requests->shellfoundry) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from requests->shellfoundry) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from requests->shellfoundry) (2019.11.28)
Requirement already satisfied, skipping upgrade: whichcraft>=0.4.0 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cookiecutter==1.6.0->shellfoundry) (0.6.1)
Requirement already satisfied, skipping upgrade: poyo>=0.1.0 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cookiecutter==1.6.0->shellfoundry) (0.5.0)
Requirement already satisfied, skipping upgrade: jinja2-time>=0.1.0 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cookiecutter==1.6.0->shellfoundry) (0.2.0)
Requirement already satisfied, skipping upgrade: binaryornot>=0.2.0 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cookiecutter==1.6.0->shellfoundry) (0.4.4)
Requirement already satisfied, skipping upgrade: future>=0.15.2 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cookiecutter==1.6.0->shellfoundry) (0.18.2)
Requirement already satisfied, skipping upgrade: jinja2>=2.7 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cookiecutter==1.6.0->shellfoundry) (2.11.1)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from ruamel.yaml->shellfoundry) (0.2.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cryptography->shellfoundry) (1.13.2)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cryptography->shellfoundry) (1.13.0)
Requirement already satisfied, skipping upgrade: arrow in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from jinja2-time>=0.1.0->cookiecutter==1.6.0->shellfoundry) (0.15.5)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from jinja2>=2.7->cookiecutter==1.6.0->shellfoundry) (1.1.1)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography->shellfoundry) (2.19)
Requirement already satisfied, skipping upgrade: python-dateutil in c:\users\dmit\pycharmprojects\pytest_framework\venv\lib\site-packages (from arrow->jinja2-time>=0.1.0->cookiecutter==1.6.0->shellfoundry) (2.8.1)
Installing collected packages: shellfoundry
  Found existing installation: shellfoundry 1.2.16
    Uninstalling shellfoundry-1.2.16:
      Successfully uninstalled shellfoundry-1.2.16
  Running setup.py install for shellfoundry ... done
Successfully installed shellfoundry-1.2.17

(venv) C:\Users\dmit\PycharmProjects\pytest_framework>cd test_gen1

(venv) C:\Users\dmit\PycharmProjects\pytest_framework\test_gen1>shellfoundry install
Shell package was successfully created:
C:\Users\dmit\PycharmProjects\pytest_framework\test_gen1\dist\test_gen1.zip
Installing package C:\Users\dmit\PycharmProjects\pytest_framework\test_gen1\dist\test_gen1.zip into CloudShell at http://192.168.85.29:9000
Successfully installed shell
</pre>
