### ISSUE TITLE
'Error' word repeats twice

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/shellfoundry#251]
### Issue details

_Error: "..." directory already exists_ message looks like _Error: Error: "broadband-media" directory already exists_

### Steps to reproduce

1. Create new shell (e.g. broadband-media)
<pre>
(shellfoundry_1.2.17) C:\Users\dmit\test_shell_4>shellfoundry new broadband-media --template gen2/broadband-media
Created shell broadband-media based on template gen2/broadband-media
</pre>
2. Create the same shell one more time
<pre>
(shellfoundry_1.2.17) C:\Users\dmit\test_shell_4>shellfoundry new broadband-media --template gen2/broadband-media
Error: Error: "broadband-media" directory already exists
</pre>

### Affected version:
1.2.17

### Affected platforms

- [x] Windows
- [x] Linux

_Please fill additional environment specific configuration_

**Comment by alexquali** [comment]
Fixed in version 1.2.21
