### ISSUE TITLE
Uninformative error message when configured domain  is incorrect

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/shellfoundry#254]
### Issue details
<pre>
(shellfoundry_1.2.17) C:\Users\dmit\Documents\Virtual_env\shellfoundry_1.2.17\Scripts>shellfoundry config
 Key                Value
------------------------------------
 domain             Global        *
 password           [encrypted]
 username           shellstest
 port               9000          *
 host               192.168.42.9
 author             Turkov
 online_mode        True
 template_location  Empty         *
 github_login       turkovda
 github_password    [encrypted]
 defaultview        gen2

* Value marked with '*' is actually the default value and has not been override by the user.

(shellfoundry_1.2.17) C:\Users\dmit\Documents\Virtual_env\shellfoundry_1.2.17\Scripts>shellfoundry list
Usage: shellfoundry list [OPTIONS]

Error: Login to CloudShell failed. Please verify the credentials in the config
</pre>

CS Rest API return informative error message:
<pre>
urllib.error.HTTPError: HTTP Error 401: Domain 'Global' doesn't exists or the user is not it's member.
</pre>

### Steps to reproduce

1. Configure incorrect domain and perform shellfoundry list command
2. Observe output

### Expected Result:
Error message should inform about incorrect domain

### Affected version:
1.2.17

### Affected platforms

- [x] Windows
- [ ] Linux

_Please fill additional environment specific configuration_

**Comment by alexquali** [comment]
Fixed in version 1.2.21
