### ISSUE TITLE
shellfoundry install fails with pip version 7.1.2

### ISSUE THREAD

**Issue by borismod** [QualiSystems/shellfoundry#60]
### Issue details

When running shellfoundry install with pip version 7.1.2 I get the following error:

c:\Users\yoram-s\git\stc_shell>shellfoundry install
shellfoundry - CloudShell shell command-line tool
Shell package was successfully created:
c:\Users\yoram-s\git\stc_shell\dist\stc-shell.zip
ERROR: unknown command "download"

I had to upgrade to latest pip (8.1.2) to get it to work.
### Steps to reproduce

Install pip version 7.1.2
### Affected version:

shellfoundry 0.0.32
pip 7.1.2
Python 2.7.10
### Affected platforms
- [x] Windows
- [ ] Linux

**Comment by doppleware** [comment]
Sounds like a release note
