### ISSUE TITLE
shellfoundry generic message is written for every command

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/shellfoundry#61]
### Issue details

""shellfoundry - CloudShell shell command-line tool"" line is written for every shellfoundry command

### Steps to reproduce

execute any command in shellfoundry

### Affected version:
0.0.32

### Affected platforms

- [ ] Windows
- [ ] Linux

_Please fill additional environment specific configuration_

**Comment by borismod** [comment]
Why do yo think it's an issue?
