### ISSUE TITLE
Usage.md is inaccurate

### ISSUE THREAD

**Issue by gsloan-qs** [QualiSystems/shellfoundry#62]
### Issue details

The Usage.md file has wrong information about the usage.

What it says:
$ pip install new nutshell

What it should be:
$ shellfoundry new nutshell

What it says:
$ pip install new nutshell --template_name=base

What it should be:
$ shellfoundryl new nutshell --template base

**Comment by borismod** [comment]
@gsloan-qs thanks for reporting. Fixed on develop branch. Will be merged to master later on.
