### ISSUE TITLE
Sonar support

### ISSUE THREAD

**Issue by ric79** [QualiSystems/shellfoundry#66]
This is not an issue.

I configured SonarQube for Python style coding monitoring.

It will be cool that:
- in .gitignore 

```
# Sonar
.sonar/
```
- when a new resource is created, on root directory, this files is added

./sonar-project.properties

```
# Required metadata
sonar.projectKey=org.sonarqube:xxxxx
sonar.projectName=Python :: xxxxxx : SonarQube Scanner
sonar.projectVersion=1.0

# Comma-separated paths to directories with sources (required)
sonar.sources=src

# Language
sonar.language=py

# Encoding of the source files
sonar.sourceEncoding=UTF-8
```

Riccardo

**Comment by borismod** [comment]
@ric79, do you need it is specific template ?

**Comment by ric79** [comment]
Just wondering if this file can be added in the Resource-clean template. If not, i will continue to add manually that code after 'shellfoundry new' command
