### ISSUE TITLE
Remove "shell not found" 

### ISSUE THREAD

**Issue by borismod** [QualiSystems/shellfoundry#92]
### Issue details

When a user installs a shell at the first time it displays:

> "shell not found" 

this is confusing, please remove

**Comment by rohithasrk** [comment]
Will be working on this.

**Comment by borismod** [comment]
@rohithasrk good luck!

**Comment by shreab373** [comment]
can I work on this?

**Comment by borismod** [comment]
@shreab373 yes, feel free to work on this.

**Comment by shreab373** [comment]
could you help me out in solving this?

**Comment by borismod** [comment]
You'd better ask @doppleware or @menib

**Comment by aritro01** [comment]
@doppleware can I take this ?

**Comment by Costya-Y** [comment]
not relevant anymore
