### ISSUE TITLE
Add a line in usage

### ISSUE THREAD

**Issue by borismod** [QualiSystems/shellfoundry#98]
### Issue details

Print the following at the bottom after the commands list:

> For help on any individual command run `shellfoundry COMMAND --help`

**Comment by Kashyap12** [comment]
hey @borismod , I am quite new to opensource, would like to contribute on this issue, can I take this up?

**Comment by borismod** [comment]
Hi @Kashyap12 

That's great that you decided to contribute to shellfoundry. I believe it's one of the most productive ways of learning how to code. This issue is a good to start with. Get familiar with the contributing guidelines and go ahead:
https://github.com/QualiSystems/shellfoundry/blob/develop/.github/contributing.md

**Comment by Kashyap12** [comment]
hi @borismod , do we have a gitter chatroom or an IRC chat, needed to discuss few things regarding this issue?

**Comment by borismod** [comment]
@Kashyap12 I do not longer maintain this repository. You may contact @menib or @doppleware with any question

**Comment by MikeinRealLife** [comment]
doesn't look like this got done, I'll take it.

**Comment by borismod** [comment]
Cool! Let me know if you need any assistance

On Mar 19, 2017 3:50 AM, "MikeinRealLife" <notifications@github.com> wrote:

doesn't look like this got done, I'll take it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/QualiSystems/shellfoundry/issues/98#issuecomment-287588218>,
or mute the thread

**Comment by shreab373** [comment]
can i work on this?

**Comment by theharshitgarg** [comment]
Hello, 
It seems this issue is not resolved yet. In case not, I am interested in working on this issue.

**Comment by borismod** [comment]
Go ahead and let me know if you need anything

**Comment by theharshitgarg** [comment]
```
For help on any individual command run shellfoundry COMMAND --help

Usage: shellfoundry [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  config    Configures global/local config values to...
  dist      Creates a deployable Shell which can be...
  extend    Creates a new shell based on a existed SOURCE...
  generate  Generates Python driver data model to be used...
  install   Installs the shell package into CloudShell
  list      Lists the available shell templates
  new       Creates a new shell based on a template
  pack      Creates a shell package
  show      Shows all versions of TEMPLATENAME
  version   Displays the shellfoundry version
```

**Comment by clarkem** [comment]
Hi, I've forked the repo, made the branch and committed the change.  Are any tests required for this prior to a PR ? 
Thanks!

**Comment by borismod** [comment]
@clarkem of course, you'll have to test your change. I would add a test that reproduces the issue you tried to solve.

**Comment by clarkem** [comment]
Hi @borismod , thanks for the response. This is a single line addition to help output, are there existing tests for this output that can be adapted?

**Comment by borismod** [comment]
It depends on where you added this line. I do not longer maintain this project. I suggest running all the tests and see whether they pass. Try asking @doppleware or @Evantal

**Comment by GalcQuali** [comment]
we will add this option under the usage section:

Usage: shellfoundry [OPTIONS] COMMAND [ARGS]...
               shellfoundry COMMAND --help

**Comment by sprajosh** [comment]
Is the issue solved? I would like to solve it if not solved already. I'm new to Open Source.

**Comment by Costya-Y** [comment]
Hi @sprajosh,

Let me check, I think it's already resolved but not yet released.

Thank you,
Costya

**Comment by Costya-Y** [comment]
Hi @sprajosh,

Sorry, it looks like it's already fixed, and will be released soon.

Thank you,
Costya
